name: Generate BhootFM RSS Feed
on:
  push:
    branches: [main]
    paths:
      - 'episodes.txt'
  workflow_dispatch:
jobs:
  Generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          submodules: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'
          
      - name: Set up FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Python script
        run: python rss-gen.py

      - name: Commit and push changes
        if: always()
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add bhootfm-rss.xml
          git diff --cached --quiet || git commit -m 'Generate BhootFM RSS Feed'
          git push "https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" main
